name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
            text: Build failed
            details: commit ${{ github.event.commits.*.url }} by ${{ github.event.commits.*.committer.username }} broke the build :(
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_API_SRV }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Test success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
            text: A new version of pokedex deployed
            details: to https://full-stack-open-pokedex-q918.onrender.com
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch